# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site - English"
weight = 1
[zh-cn]
languageName = "Chinese"
languagedirection = "ltr"
title = "Example Site - Chinese"
weight = 1
